name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull the Docker image.
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend-ci:latest

      - name: Delete the old Docker container.
        run: sudo docker rm -f backend-ci-container || true

      - name: Run the Docker container.
        run: sudo docker run -d --name backend-ci-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend-ci:latest
